### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by arshadcair** [NVlabs/STEP#13]
Thank you for sharing the code of your wonderful work.
After setting up the environment, I tried the demo.py program on my own video clip having 64 frames.
I am getting the above mentioned error in following line:  
    for _, (images, tubes, infos) in enumerate(dataloader):
Have you ever faced this error? What could be possible solution.
Thanks.

**Comment by xyang35** [comment]
Thank you for your interest in our work! 
It seems that there's an invalid operation between "None" and a 'int' type object. My guess is that it may occur somewhere inside the data augmentation process. Please debug your data loading process and check whether there're variables that are not given or images that are not loaded.
I'm happy to help if you provide more details  later.

**Comment by geeekkkkkk** [comment]
Thank you so much. The issue was resolved. I was using incorrect frame name. it should start from frame_0000.jpg.

**Comment by xyang35** [comment]
That's great!

**Comment by DevTech15** [comment]
hello @geeekkkkkk which script you used for extracting frames?
i am using this script which generates frames with these names
0.jpg
1.jpg
.
.
.
.
100.jpg
.
.
.4000.jpg

And hence i am having same error as your because in demo.py im_format = 'frame%04d.jpg' this sequence i think mismatches and hence creates problem
any help will be highly appreciated

`
# Importing all necessary libraries 
import cv2 
import os 
import numpy as gfg
import PIL
from PIL import Image
  
# Read the video from specified path 
cam = cv2.VideoCapture("/videopath.mkv") 
  
try: 
      
    # creating a folder named data 
    if not os.path.exists('data'): 
        os.makedirs('data') 
  
# if not created then raise error 
except OSError: 
    print ('Error: Creating directory of data') 
  
# frame 
currentframe = 0
images = []
while(True): 
      
    # reading from frame 
    ret,frame = cam.read() 
  
    if ret: 
        # if video is still left continue creating images 
        name = 'basepath/video_id1/' + str(currentframe) + '.jpg'
        print ('Creating...' + name) 
  
        # writing the extracted images 
        cv2.imwrite(name,frame)
        images.append(frame)
        #imageToMatrice = gfg.asarray()
  
        # increasing counter so that it will 
        # show how many frames are created 
        currentframe += 1
    else: 
        break
  
# Release all space and windows once done 
cam.release() 
cv2.destroyAllWindows()`
